"""Collection of slaps.

Authors (telegrams) - @doitforgachi, @calldoctor
"""

SLAPS = [
    'init ударил target писюном ',
    'init ударил target бутылкой',
    'init ударил target carasiqueом',
    'init ударил target куриной ножкой',
    'init ударил target самотыком',
    'init ударил target сковородкой',
    'init ударил target банхамером',
    'init ударил target дакимакурой (а он и не против)',
    'init ударил target этим говнокодом',
    'init ударил target Капиталом',
    'init обтер лицо target яйцами',
    'init пукнул в лицо target',
    'init пукнул в лицо target гринтекстом',
    'init дал target пощёчину',
    'init трахнул мамку target',
    'init плюнул в борщ target',
    'init поковырялся в заду target трубкой',
    'init прокрался к target и пересыпал соль и сахар',
    'init одел клетку на член target',
    'init угостил target отравленным пирожком',
    'init донёс ФСБ на target',
    'init убил пёсика target',
    'init угнал тачку target',
    'init плюнул target в компот',
    'init укусил за писюн target',
    'init наябедничал мамке target',
    'init угостил target пирожком с говном',
    'init чихнул в target гриппом',
    'init чихнул в target китайской чумой',
    'init увел тяночку у target',
    'init подложил на стул target кнопку',
    'init дал target поджопник',
    'init отвесил target подзатыльник',
    'init нассал в кружку target',
    'init спёр трусики target',
    'init продырявил носки target',
    'init прокрался к target и укоротил ему хуй',
    'init сделал target кусь',
]
